#!/usr/bin/env bash

# rbw git-credential helper
# Based on https://github.com/lastpass/lastpass-cli/blob/master/contrib/examples/git-credential-lastpass

# A credential helper for git to retrieve usernames and passwords from bw.
# For general usage, see https://git-scm.com/docs/gitcredentials.
# Here's a quick version:
# 1. Put this somewhere in your path.
# 2. git config --global credential.helper bw

declare -A params

if [ "x$1" == "xget" ]; then
    read line
    while [ -n "$line" ]; do
        key=${line%%=*}
        value=${line#*=}
        params[$key]=$value
        read line
    done

    if [ "x${params['protocol']}" != "xhttps" ]; then
        exit
    fi

    if [ -z "${params["host"]}" ]; then
        exit
    fi

    bw status | grep 'unlocked' > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo "Please login/unlock to use git credential helper" > /dev/stderr
        exit
    fi

    user=`bw get username ${params["host"]}`
    pass=`bw get password ${params["host"]}`

    if [ "x$user" == "x" ] || [ "x$pass" == "x" ]; then
        echo "Couldn't find host '${params["host"]}' in bw DB." > /dev/stderr
        exit
    fi

    echo username=$user
    echo password=$pass
fi
